### ISSUE TITLE
After being killed by another player you respawn with an completely empty inventory (no weapons)

### ISSUE THREAD

**Issue by qwc** [Terasology/LightAndShadow#109]
In the Teracon 2019 multiplayer playtest we encountered issues with the combat system. 

- Empty inventory and toolbar (Tuesday 15. Oct)
When using the latest master of before the teracon and applying the PR #107 we encountered the issue, that when you are being killed by another player you respawn with an empty inventory and an empty toolbar so you cannot fight anymore. 

- An additional quirk i cannot remember correctly right now, highlighting @skaldarnar in the hope that he can add his part for that one.

**Comment by ahv15** [comment]
I thought this was intentional , if this is still an issue can I resolve this?

**Comment by skaldarnar** [comment]
Hm, I don't think this was fully intentional that you don't have _any_ weapons after respawn. The same was as it is not intentional to have a full-fledged weapon arsenal at your hands when starting the game. 

I think this issue was meant to track that a player should have _some_ kind of starting weapon to be able to participate in the fight again.

**Comment by ahv15** [comment]
I understood that later on so I suggested creating a new RespawnInventory to fix this in my proposal and add the appropriate utilities to give the items in the inventory module.
