### ISSUE TITLE
Black borders around blocks

### ISSUE THREAD

**Issue by getsmp** [Terasology/LightAndShadow#2]
Log: http://pastebin.com/V3ingzeZ
logs/shaders folder: http://www4.zippyshare.com/v/bPimObkx/file.html
![terasology-150111161742-1152x700](https://cloud.githubusercontent.com/assets/9785946/5695231/a75ec2d8-99a7-11e4-9e28-eb5880318e59.png)

Thanks for replying.

**Comment by skaldarnar** [comment]
Hey @getsmp - the borders around blocks are actually a style choice for Light and Shadow :smile: Might not be as obvious as it should be, since the texturing is not consistent yet.

**Comment by getsmp** [comment]
But.. what if I want to use a module that requires Light and Shadow and I don't like these borders? Maybe somehow to turn them off?

**Comment by skaldarnar** [comment]
You should be able to just override the textures (the borders are just part of the textures, no shader-magic applied here) :wink:

**Comment by Cervator** [comment]
Yup, this is a style choice - Light & Shadow is supposed to be a crazy Alice in Wonderland world, with lots of gaming references, so the world looks a bit like a board game :-)

No other modules currently depend on Light & Shadow - it is its own thing, and not really meant to be enabled piecemeal along with other modules. But any new module can be built to depend on the LightAndShadowResources module (where the textures live) then tweak at the exact config, picking and choosing what it wants to have active, making new blocks and assets.

But that takes a whole new module, since it would be a tweak to code and assets - this isn't something you'd be able to normally configure with the existing module. Unless the author wanted to make it an option to selectively ignore certain textures, anyway.
