### ISSUE TITLE
Custom ChunkGenerator based on a static heightmap

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#25]
We need a clone of `BasicHMTerrainGenerator` that reads a different heightmap that'll be used every time for L&S games. Some ideas - not sure which are appropriate for use within this chunk gen:

- [ ] Can we draw biome detail straight from the heightmap and cut the world into the 9 distinct zones making up the world?
      Reference: http://forum.terasology.org/attachments/map-png.1021/
- [ ] Could biomes be made to pick the correct "tree" type for the zone at hand?
- [ ] Could static locations (the castles, villages, and central parchisi board) be placed via the heightmap somehow?

Heightmap should also be fairly small - the L&S world (starting out at least) should be pretty tiny to make it easier to deal with. Maybe investigate how the edges of the world would handle?

## Related Issues

Art assets for different tree types and other environmental props:

- Backgammon Trees (https://github.com/Terasology/LightAndShadow/issues/15)
- Billiard Bluff Trees (https://github.com/Terasology/LightAndShadow/issues/17)
- Card Crag "Boulders"(https://github.com/Terasology/LightAndShadow/issues/16)
- Domino Pieces (https://github.com/Terasology/LightAndShadow/issues/18)
- Poker Chip Trees (https://github.com/Terasology/LightAndShadow/issues/9)

New generators for such trees:

- Custom Tree Generator (https://github.com/Terasology/LightAndShadow/issues/10)

**Comment by jdrueckert** [comment]
This issue is related to the original vision for LaS which diverges from the path currently taken (fast-paced capture-the-flag). It might be taken up again in the future once we have support for providing and selecting from a pool of maps, but until then I'll close it as there's a bunch of other improvements (including but not limited to the state machine rewrite) necessary for LaS.
The art assets / tree types issues are still valid though, as they could theoretically also be used with the current map.
