### ISSUE TITLE
Pathing for mobs

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#40]
@synopia has been previously working on a pathfinding module. Hoping to make that part of round one when we have creatures to move around :-)
##

**Comment by DPirate** [comment]
I would like to look into it, where can I start ?

Is it supposed to be for a single target?

**Comment by skaldarnar** [comment]
Hi @DPirate. 

Light and Shadows has some nice art assets, including some mobs (you can read more about the lore [in the forums](http://forum.terasology.org/threads/las-light-and-shadow-art-discussion.762/). For a start, you can investigate [WildAnimals](https://github.com/Terasology/WildAnimals) which has some _stray_ behavior for deer. 
The pathing for LaS mobs will depent on the game mode, but in theory we want mobs to reach a specfic position, do some actions, and react to their environment. Hop on our IRC so we can figure out a proper scope for this. Maybe @rzats also has some ideas.

**Comment by DPirate** [comment]
Hello,

I was thinking about a system which generates a graph of specific blocks ( using coords and some filters) in the loaded chunks  then pass it to any entity or mob to generate their on path.
Do tell me when will you be available on IRC and your chat name :), mine is the same.

**Comment by skaldarnar** [comment]
The basic pathfinding is already working. GooeysQuest has a skeleton mob that will hunt you down, so that's another reference to look at. 
Probably this issues needs some more work on general gameplay for LigthAndShadow before it can be worked on (properly). Are you interested in any other issue from [this list](https://github.com/MovingBlocks/Terasology/issues)? 

Just hop in IRC anytime you want, usually someone will be around. I'm in central europe, so ECT+2 evenings are usually a good time to catch me ;-)

**Comment by jdrueckert** [comment]
While minion management is certainly on the roadmap for LaS, it's currently not supported and there's more pressing matters at the moment (including but not limited to the state machine rewrite) until there's capacity to implement it (or integrate minion management from [MasterOfOreon](https://github.com/Terasology/MasterOfOreon)) in the first place. Irrespective of that, [FlexiblePathfinding](https://github.com/Terasology/FlexiblePathfinding/) provides the pathfinding logic for AI entities with [Behaviors](https://github.com/Terasology/Behaviors), so this issue can be closed.
