### ISSUE TITLE
Primitive combat (GelCube style)

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#49]
This is intended as a minimal "combat" system using the super simple technique used for the "danger cubes". If enabled currently (via portals module, spawned by greenportal) they will actively hunt down the player and cause damage. That can probably be hacked about a bit to make them damage each other / other gelcubes / applied to L&S mobs.

This would be a temp solution that would work in the develop branch (no portals stuff converted for multiplayer yet). It should theoretically allow the two sides to send waves of symmetrical violence toward each other in perfect balance, until the player disturbs it (with health potions available!)

Maybe something learned from this can be applied to improved combat over time later. Maybe @MarcinSc will be interested :-)
##

**Comment by Cervator** [comment]
Bump - we now can has [CombatSystem](https://github.com/Terasology/CombatSystem) and aggressive/hostile deer from [WildAnimals](https://github.com/Terasology/WildAnimals) that will attack the player! That might be enough to also start applying it to Light & Shadow (which I think @dkambersky has expressed an interest in, although that might be with v2 of the behavior trees)

**Comment by jdrueckert** [comment]
As mentioned in the above comment, logic for this kind of behavior exists, but I don't think it's relevant for the current short- to mid-term vision for LaS anymore. If minions are introduced that can be spawned by a player, it would be nice to have them attack players of the enemy team automatically, but until then, I don't think this issue is needed.
