### ISSUE TITLE
Improve magic dome

### ISSUE THREAD

**Issue by skaldarnar** [Terasology/LightAndShadow#6]
The magic dome implementation has some outstanding quirks:
-  [ ] The force field push throws the player slightly in the air. If outside the dome (or still on the border after the push) the vertical velocity will add, throwing the player higher and higher into the air. One way to check for this is to make sure that the impulse does _not_ cause the player to be further away from the center than before.
- [ ] Instead of pushing the player always back inside the dome it may be better to push away from the sphere (-> back inside if coming from inside, further away outside if trying to get in).
##

**Comment by krishnarb3** [comment]
Does the first point mean that the player should not be able to double jump?

**Comment by Cervator** [comment]
Heya @krishnarb3 - the multi-jump functionality is separate from this.

The problem is that if you somehow get *outside* the top, say on the very top of it, the impulse's built in upward motion pushes you further away from the center.

Probably instead of it being a set push away from the dome + up it should be away from the top + toward the dome's center. Or maybe a little up is OK but only if the direction doesn't result in further distance from the center, as @skaldarnar suggests.

**Comment by krishnarb3** [comment]
Thank you.
Has this already been done in the feature-magic_dome branch?
