### ISSUE TITLE
Player does not face the opponent's base on getting spawned

### ISSUE THREAD

**Issue by darshan3** [Terasology/LightAndShadow#86]
The player originally teleports to the base and faces a lateral direction (for both red/black teams). They should face each other's base on getting spawned in the play area.

**Comment by jdrueckert** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix spawn orientation of player](https://trello.com/c/XAZIRJY6/28-fix-spawn-orientation-of-player)

**Comment by grumblefoot** [comment]
After doing some testing, this issue is dependent on player facing when clicking on the teleport block. The player appears facing in whichever orientation they were before the teleport. A fix would likely involve changing the players facing right after the activation of the block, but before they are respawned.

**Comment by skaldarnar** [comment]
This was fixed by https://github.com/Terasology/LightAndShadow/pull/229
